/**
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */

/**
Time complexity O(n) + O(m) where "n" is "s" and "m" is "t"
Memory - O(n) where "n" is size of "s"
*/
class Solution {
    func findTheDifference(_ s: String, _ t: String) -> Character {
        var dict : [Character: Int] = [:]
        var r : Character?

        for ch in s{
            if dict[ch] != nil{
                dict[ch]! += 1
            }else{
                dict[ch] = 0
            }
        }

        for ch in t{
            if dict[ch] != nil{
                if dict[ch]! == 0 {
                    dict.removeValue(forKey: ch)
                }else{
                    dict[ch]! -= 1
                }
            }else{
                r = ch
                break
            }
        }

        return r!
    }
}